apiVersion: retry.tekton.dev/v1alpha1
kind: PipelineRetryPolicy
metadata: {name: unknown-policy-key}
spec:
  pipelineRef: delivery
  tasks:
    scan: {retryWith: [build]}
    biuld: {blocksResume: true}
